name: docker container node
on: push

jobs:
  docker_container:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.16
    steps:
      - name: node image and version check
        run: |
          node -v
          cat /etc/os-release
