name: docker container python
on: push

jobs:
  docker_container:
    runs-on: ubuntu-latest
    container:
      image: python:3.10.9-alpine3.16
    steps:
      - name: python image and version check
        run: |
          python --version

      - name: python table
        run: |
          num = 181
          for i in range(1, 11):
            print(num, 'x', i, '=', num*i)
